name: PaperConnector
version: '1.0'
main: net.astopia.paperconnector.PaperConnectorPlugin
loader: net.astopia.paperconnector.ConnectorPluginLoader
description: PaperConnector
api-version: '1.21.4'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: true
      join-classpath: true