name: KnowledgeSystem
version: '1.0'
main: net.unnamed.minecraft.paper.knowledge.KnowledgeSystemPlugin
description: Knowledge
api-version: '1.21.4'
dependencies:
  bootstrap:
    EssentialsA:
      load: BEFORE
      required: true
      join-classpath: true
  server:
    EssentialsA:
      load: BEFORE
      required: true
      join-classpath: true